# Generated by Django 5.1.5 on 2025-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokadmink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='YourModel',
            new_name='TiktokDataORM',
        ),
    ]
