# Generated by Django 5.1.5 on 2025-01-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokadmink', '0002_cookiefile_rename_yourmodel_tiktokdataorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiefile',
            name='content',
            field=models.JSONField(),
        ),
    ]
