# Generated by Django 5.1.5 on 2025-01-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokadmink', '0003_alter_cookiefile_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiefile',
            name='content',
            field=models.TextField(),
        ),
    ]
