# Generated by Django 5.1.5 on 2025-02-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokadmink', '0004_alter_cookiefile_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiktokBreakoutSongsORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('artist', models.CharField(max_length=255, verbose_name='Исполнитель')),
                ('value', models.TextField(verbose_name='Дополнительная информация')),
                ('type', models.CharField(choices=[('breakout_song', 'Breakout Song')], max_length=20, verbose_name='Тип данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Взлетающие песни',
                'verbose_name_plural': 'Взлетающие песни',
            },
        ),
        migrations.CreateModel(
            name='TiktokHashtagsORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('value', models.TextField(verbose_name='Дополнительная информация')),
                ('type', models.CharField(choices=[('hashtag', 'Hashtag')], max_length=20, verbose_name='Тип данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Хештеги',
                'verbose_name_plural': 'Хештеги',
            },
        ),
        migrations.CreateModel(
            name='TiktokSongsORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('artist', models.CharField(max_length=255, verbose_name='Исполнитель')),
                ('value', models.TextField(verbose_name='Дополнительная информация')),
                ('type', models.CharField(choices=[('song', 'Song')], max_length=20, verbose_name='Тип данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Песни',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.DeleteModel(
            name='TiktokDataORM',
        ),
    ]
