# Generated by Django 5.1.5 on 2025-02-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokadmink', '0005_tiktokbreakoutsongsorm_tiktokhashtagsorm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokbreakoutsongsorm',
            name='type',
            field=models.CharField(choices=[('breakout_song', 'Breakout Song'), ('author', 'Author')], max_length=20, verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='tiktoksongsorm',
            name='type',
            field=models.CharField(choices=[('song', 'Song'), ('author', 'Author')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
