# Generated by Django 5.1.5 on 2025-02-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokadmink', '0006_alter_tiktokbreakoutsongsorm_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiktokbreakoutsongsorm',
            old_name='artist',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='tiktoksongsorm',
            old_name='artist',
            new_name='author',
        ),
    ]
