# Generated by Django 5.1.5 on 2025-02-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiktokadmink', '0007_rename_artist_tiktokbreakoutsongsorm_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CookieFile',
            new_name='CookieFileORM',
        ),
    ]
